name: Test

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.3.5', '3.1', '3.0', '2.7.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: RUBYOPT='--disable-did_you_mean' bundle install
    - name: Run tests
      run: bundle exec rspec
